services:
  web:
    build: .
    ports: ["8000:8000"]
    environment:
      - DB_USER=user
      - DB_PASSWORD=1256923
      - DB_NAME=novelstack
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=asdfhjasdhfkjahsdjkfh
      - DEBUG=True
    command: sh -c "python manage.py migrate && gunicorn novelstack.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1256923
      - POSTGRES_DB=novelstack
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d novelstack"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: