# Generated by Django 6.0.6 on 2026-06-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chapters', models.IntegerField()),
                ('release_date', models.DateField()),
                ('classification', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus')], default='ongoing', max_length=15)),
            ],
        ),
    ]
