# Generated by Django 6.0.6 on 2026-07-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='wln_series_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
