# Generated by Django 6.0.6 on 2026-07-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_wln_series_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='wln_series_id',
            new_name='anilist_id',
        ),
    ]
