# Generated by Django 6.0.6 on 2026-07-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_wln_series_id_book_anilist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='anilist_cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
