# Generated by Django 6.0.6 on 2026-07-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_genre_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
