# Generated by Django 6.0.6 on 2026-07-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('hiatus', 'Hiatus'), ('cancelled', 'Cancelled'), ('not_yet_released', 'Not Yet Released')], default='ongoing', max_length=20),
        ),
    ]
