# Generated by Django 6.0.6 on 2026-07-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='anilist_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
